steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/elevatecowdev/elevate-tapinout-prevendas:$BUILD_ID', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/elevatecowdev/elevate-tapinout-prevendas:$BUILD_ID']
images:
  - 'gcr.io/elevatecowdev/elevate-tapinout-prevendas:$BUILD_ID'
