steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:$BUILD_ID'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:$BUILD_ID'
      - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:latest'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tapinout-landing-$_ENVIRONMENT'
      - '--image'
      - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:$BUILD_ID'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
      - '--platform'
      - 'managed'

images:
  - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:$BUILD_ID'
  - 'gcr.io/$PROJECT_ID/tapinout-landing-$_ENVIRONMENT:latest' 